import { StyleSheet } from "react-native";

export const loginStyles = StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: "#f0f4ff",
    justifyContent: "center",
    alignItems: "center",
  },
  topBlob: {
    position: "absolute",
    top: -80,
    left: -80,
    width: 280,
    height: 280,
    borderRadius: 140,
    backgroundColor: "rgba(37, 99, 235, 0.12)",
  },
  bottomBlob: {
    position: "absolute",
    bottom: -60,
    right: -60,
    width: 220,
    height: 220,
    borderRadius: 110,
    backgroundColor: "rgba(16, 185, 129, 0.10)",
  },
  card: {
    backgroundColor: "#ffffff",
    borderRadius: 28,
    padding: 32,
    width: "90%",
    maxWidth: 380,
    elevation: 12,
    shadowColor: "#2563eb",
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.12,
    shadowRadius: 20,
  },
  iconWrap: {
    alignSelf: "center",
    width: 72,
    height: 72,
    borderRadius: 36,
    backgroundColor: "#eff6ff",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 12,
  },
  iconText: { fontSize: 36 },
  brand: {
    textAlign: "center",
    fontSize: 26,
    fontWeight: "800",
    color: "#1e3a8a",
    letterSpacing: 0.5,
  },
  sub: {
    textAlign: "center",
    fontSize: 12,
    color: "#64748b",
    marginTop: 4,
    letterSpacing: 0.3,
  },
  divider: {
    height: 1,
    backgroundColor: "#e2e8f0",
    marginVertical: 24,
  },
  label: {
    fontSize: 12,
    fontWeight: "700",
    color: "#2563eb",
    marginBottom: 6,
    marginLeft: 2,
    letterSpacing: 0.5,
    textTransform: "uppercase",
  },
  documentRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 16,
  },
  documentTypeButton: {
    flex: 0.28,
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 12,
    backgroundColor: "#f8fafc",
    borderWidth: 1.5,
    borderColor: "#e2e8f0",
    paddingVertical: 13,
    marginRight: 8,
  },
  documentTypeText: {
    fontSize: 16,
    fontWeight: "700",
    color: "#1e293b",
  },
  documentInput: {
    flex: 0.72,
  },
  input: {
    backgroundColor: "#f8fafc",
    borderWidth: 1.5,
    borderColor: "#e2e8f0",
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 13,
    fontSize: 16,
    color: "#1e293b",
    marginBottom: 16,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.35)",
    justifyContent: "center",
    alignItems: "center",
    padding: 20,
  },
  modalContent: {
    width: "100%",
    backgroundColor: "#fff",
    borderRadius: 18,
    padding: 20,
  },
  modalTitle: {
    fontSize: 16,
    fontWeight: "800",
    marginBottom: 16,
    color: "#1e293b",
  },
  modalOption: {
    paddingVertical: 14,
    paddingHorizontal: 12,
    borderRadius: 12,
    backgroundColor: "#f8fafc",
    marginBottom: 10,
  },
  modalOptionSelected: {
    backgroundColor: "#eef2ff",
  },
  modalOptionText: {
    fontWeight: "700",
    color: "#1e293b",
  },
  modalCancel: {
    marginTop: 8,
    paddingVertical: 14,
    borderRadius: 12,
    backgroundColor: "#e2e8f0",
    alignItems: "center",
  },
  modalCancelText: {
    fontWeight: "700",
    color: "#1e293b",
  },
  btn: {
    backgroundColor: "#2563eb",
    borderRadius: 14,
    paddingVertical: 16,
    alignItems: "center",
    marginTop: 8,
    elevation: 4,
    shadowColor: "#2563eb",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
  },
  btnText: {
    color: "#fff",
    fontWeight: "800",
    fontSize: 15,
    letterSpacing: 1,
  },
  hint: {
    textAlign: "center",
    fontSize: 11,
    color: "#94a3b8",
    marginTop: 20,
  },
});
